version: '3.2'
services:
  api:
    build: .
    command: sh -c "yarn start:dev"
    environment:
      #APP
      NODE_ENV: development

    volumes:
      - .:/app
      - ~/.config:/root/.config
      - /node_modules
    ports:
      - '3001:3001'