version: '3.2'
services:
  api:
    build: .
    command: sh -c "yarn start:dev"
    environment:
      #APP
      NODE_ENV: development
    depends_on:
      - db_local
    volumes:
      - .:/app
      - ~/.config:/root/.config
      - /node_modules
    ports:
      - '3001:3001'
  db_local:
    image: postgres:latest
    environment:
      POSTGRES_DB: reparo_rapido
      POSTGRES_USER: reparo_rapido
      POSTGRES_PASSWORD: reparo_rapido
    ports:
      - 5432:5432